version: '2.1'

services:
  test-service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/rp/test-service
    ports:
      - $SERVER_PORT:$SERVER_PORT
