java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/rp/test-service:latest'
  ingressHost: rp-test-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rp
  environment:
